id = "zed-extension-shuttle-notation"
name = "Shuttle Notation Syntax"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "Syntax highlighting for shuttle"
repository = "https://github.com/estrandv/zed-extension-shuttle-syntax"

[grammars.shuttle]
repository = "https://github.com/estrandv/tree-sitter-shuttle-notation"
rev = "70739704034c343de7bc7c4a9e033df1c0297f5d"
