id = "zed-extension-shuttle-notation"
name = "Shuttle Notation Syntax"
version = "0.0.1"
schema_version = 1
authors = ["estrandv <emil.strandvik@gmail.com>"]
description = "Syntax highlighting for shuttle and jdw-billboarding"
repository = "https://github.com/estrandv/zed-extension-shuttle-syntax"

[grammars.shuttle]
repository = "https://github.com/estrandv/tree-sitter-shuttle-notation"
rev = "05d9cfbe7faaebafecacc40f2faeda4c64ad86fa"

[grammars.jdw_billboarding]
repository = "https://github.com/estrandv/tree-sitter-jdw-billboarding"
rev = "fff4bf065dc898ce485e137d49ae434b87055a09"
