id = "zed-extension-shuttle-notation"
name = "Shuttle Notation Syntax"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "Syntax highlighting for shuttle"
repository = "https://github.com/estrandv/zed-extension-shuttle-syntax"

[grammars.shuttle]
repository = "https://github.com/estrandv/tree-sitter-shuttle-notation"
rev = "942160268105cba7bf14ad726dbe88177fc67946"
